
// <auto-generated/>
// Do not modify by hand!
// To update this file, use "Tools -> UnityCodeGen -> Generate" main menu item

using System;
using Newtonsoft.Json;
using CherryFramework.DataModels;
using InsideVentura.DataModels.Templates;

namespace GeneratedDataModels
{
    [Serializable]
    public class PlayerDataModel : DataModelBase
    {
        private PlayerData _template;
        
        public PlayerDataModel() : base()
        {
			_template = new();
			Getters.Add(nameof(money), new Func<System.Single>(() => money));
			Setters.Add(nameof(money), new Action<System.Single>(o => money = o));
			moneyAccessor = new Accessor<System.Single>(this, nameof(money));

			Getters.Add(nameof(currentHealth), new Func<System.Single>(() => currentHealth));
			Setters.Add(nameof(currentHealth), new Action<System.Single>(o => currentHealth = o));
			currentHealthAccessor = new Accessor<System.Single>(this, nameof(currentHealth));

			Getters.Add(nameof(mana), new Func<System.Single>(() => mana));
			Setters.Add(nameof(mana), new Action<System.Single>(o => mana = o));
			manaAccessor = new Accessor<System.Single>(this, nameof(mana));

			Getters.Add(nameof(maxMana), new Func<System.Single>(() => maxMana));
			Setters.Add(nameof(maxMana), new Action<System.Single>(o => maxMana = o));
			maxManaAccessor = new Accessor<System.Single>(this, nameof(maxMana));


        }
		
		public PlayerDataModel(PlayerData source) : this()
        {
	        if (source != null)
	        {
		        if (source is ICloneable cloneable)
		        {
			        _template = cloneable.Clone() as PlayerData;
		        }
		        else
		        {
			        throw new ArgumentException($"[{this.GetType().Name}] Tried to create new model with template source, but source is not ICloneable, which is not allowed!");
		        }
	        }
	        else
	        {
		        throw new ArgumentNullException(nameof(source));
	        }
        }
        
        // ReSharper disable InconsistentNaming

        public System.Single money
        {
            get => _template.money;
            set { _template.money = value;
            Send<System.Single>(nameof(money), value); }
        }     
        [JsonIgnore]  
        public Accessor<System.Single> moneyAccessor;

        public System.Single currentHealth
        {
            get => _template.currentHealth;
            set { _template.currentHealth = value;
            Send<System.Single>(nameof(currentHealth), value); }
        }     
        [JsonIgnore]  
        public Accessor<System.Single> currentHealthAccessor;

        public System.Single mana
        {
            get => _template.mana;
            set { _template.mana = value;
            Send<System.Single>(nameof(mana), value); }
        }     
        [JsonIgnore]  
        public Accessor<System.Single> manaAccessor;

        public System.Single maxMana
        {
            get => _template.maxMana;
            set { _template.maxMana = value;
            Send<System.Single>(nameof(maxMana), value); }
        }     
        [JsonIgnore]  
        public Accessor<System.Single> maxManaAccessor;

        // ReSharper restore InconsistentNaming
    }
}
